.PHONY: clean
clean:
	make clean -C abstract_memory
	make clean -C abstract_channel
	make clean -C configuration_reader
	make clean -C rtl_converter
	make clean -C drive_inserter
	make clean -C utils
	rm -rf *.pyc __pycache__ parsetab.py *.out
