.PHONY: clean
clean:
	make clean -C channel
	make clean -C dualport
	make clean -C generate_statement
	make clean -C hierarchy
#	make clean -C mips
	make clean -C pointer_chain
	make clean -C singleport
	make clean -C userdrive
