TOPMODULE=userlogic
RTL=userlogic.v
TEST=testbench.v
USERTEST=--usertest=$(TEST)
MEM=../mem-incr.hex
MEMIMG=--memimg=$(MEM)
ROOTDIR=../../../
CONFIG=$(ROOTDIR)/input/default.config
INCLUDE=-I $(ROOTDIR)/include/
include $(ROOTDIR)/input/base.mk
