TOPMODULE=userlogic
RTL=userlogic.v
TEST=testbench.v
USERTEST=--usertest=$(TEST)
MEM=../mem-incr.hex
MEMIMG=--memimg=$(MEM)
ROOTDIR=../../
CONFIG=$(ROOTDIR)/config/default.config
INCLUDE=-I $(ROOTDIR)/include/
include $(ROOTDIR)/base.mk
